#!/usr/bin/env python3
"""Visualize molecular orbital cube files in a web browser using py3Dmol.

Standalone script — does not depend on APEX_CAS.  Reads one or more .cube
files generated by PySCF (or any quantum chemistry package) and renders
isosurfaces (positive / negative phases) in an interactive 3D viewer.

Usage:
    # Single orbital
    python view_orbital.py orbital.cube

    # Adjust isovalue
    python view_orbital.py orbital.cube --isoval 0.03

    # Batch view — generates one HTML per cube, opens the first
    python view_orbital.py orb_*.cube

    # Custom colours and output
    python view_orbital.py orbital.cube --pos-color blue --neg-color red --output my_view.html

Requirements:
    pip install py3Dmol
"""

import argparse
import glob
import os
import sys
import webbrowser


def view_cube(
    cube_path: str,
    isoval: float = 0.04,
    opacity: float = 0.85,
    pos_color: str = "blue",
    neg_color: str = "red",
    bg_color: str = "black",
    style: str = "stick",
    width: int = 900,
    height: int = 700,
    output_html: str = None,
    open_browser: bool = True,
    title: str = None,
) -> str:
    """Render a single cube file as an interactive HTML page.

    Returns the absolute path of the written HTML file.
    """
    import py3Dmol

    with open(cube_path) as f:
        cube_data = f.read()

    if title is None:
        title = os.path.basename(cube_path)

    view = py3Dmol.view(width=width, height=height)

    # Positive isosurface
    view.addVolumetricData(cube_data, "cube", {
        "isoval": isoval,
        "color": pos_color,
        "opacity": opacity,
        "smoothness": 5,
    })

    # Negative isosurface
    view.addVolumetricData(cube_data, "cube", {
        "isoval": -isoval,
        "color": neg_color,
        "opacity": opacity,
        "smoothness": 5,
    })

    # Molecular structure (atom coords are embedded in the cube file)
    view.addModel(cube_data, "cube")
    if style == "ball-stick":
        view.setStyle({"stick": {}, "sphere": {"scale": 0.3}})
    elif style == "sphere":
        view.setStyle({"sphere": {"scale": 0.5}})
    else:
        view.setStyle({"stick": {}})

    view.setBackgroundColor(bg_color)
    view.zoomTo()

    # Write HTML
    if output_html is None:
        stem = os.path.splitext(os.path.basename(cube_path))[0]
        output_html = f"{stem}_viewer.html"

    html_path = os.path.abspath(output_html)

    # Inject title as HTML heading
    view.write_html(html_path, fullpage=True)
    with open(html_path, "r") as f:
        html = f.read()
    title_line = f'<h3 style="color:white;font-family:monospace;margin:8px;">{title}</h3>'
    html = html.replace("<body>", f"<body>\n{title_line}")
    with open(html_path, "w") as f:
        f.write(html)

    print(f"  Written: {html_path}")
    return html_path


def view_multi_cubes(
    cube_paths: list[str],
    isoval: float = 0.04,
    opacity: float = 0.85,
    pos_color: str = "blue",
    neg_color: str = "red",
    bg_color: str = "black",
    style: str = "stick",
    width: int = 900,
    height: int = 700,
    output_html: str = "orbital_gallery.html",
    open_browser: bool = True,
) -> str:
    """Render multiple cube files into a single gallery HTML with navigation.

    Returns the absolute path of the written HTML file.
    """
    import py3Dmol

    n = len(cube_paths)
    print(f"Building gallery with {n} orbitals ...")

    # --- Build HTML manually with embedded 3Dmol.js ---
    # This gives us full control over layout and navigation.
    js_cdn = "https://cdn.jsdelivr.net/npm/3dmol@2.4.0/build/3Dmol-min.js"

    # Read all cube data upfront
    cubes = []
    for p in cube_paths:
        with open(p) as f:
            cubes.append(f.read())

    labels = [os.path.basename(p) for p in cube_paths]

    # Build JavaScript for each viewer
    viewer_scripts = []
    for i, (cube_data, label) in enumerate(zip(cubes, labels)):
        # Escape cube data for embedding in JS string
        escaped = cube_data.replace("\\", "\\\\").replace("`", "\\`").replace("$", "\\$")
        script = f"""
        (function() {{
            var view{i} = $3Dmol.createViewer("viewer_{i}",
                {{backgroundColor: "{bg_color}"}});
            view{i}.addVolumetricData(`{escaped}`, "cube",
                {{isoval: {isoval}, color: "{pos_color}", opacity: {opacity}, smoothness: 5}});
            view{i}.addVolumetricData(`{escaped}`, "cube",
                {{isoval: {-isoval}, color: "{neg_color}", opacity: {opacity}, smoothness: 5}});
            view{i}.addModel(`{escaped}`, "cube");
            view{i}.setStyle({{stick: {{}}}});
            view{i}.zoomTo();
            view{i}.render();
        }})();
        """
        viewer_scripts.append(script)

    # Build HTML
    nav_items = "\n".join(
        f'<button onclick="show({i})" id="btn_{i}" '
        f'style="margin:2px;padding:6px 12px;cursor:pointer;'
        f'font-family:monospace;font-size:11px;">{lab}</button>\n'
        for i, lab in enumerate(labels)
    )

    viewer_divs = "\n".join(
        f'<div id="viewer_{i}" style="width:{width}px;height:{height}px;'
        f'position:absolute;top:50px;left:0;display:none;"></div>\n'
        for i in range(n)
    )

    all_scripts = "\n".join(viewer_scripts)

    html = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Orbital Gallery</title>
<script src="{js_cdn}"></script>
<style>
body {{ margin:0; padding:0; background:{bg_color}; font-family:monospace; overflow:hidden; }}
#nav {{ position:fixed; top:0; left:0; right:0; z-index:100;
        background:#222; padding:6px; display:flex; flex-wrap:wrap; gap:2px; }}
#nav button {{ border:1px solid #555; background:#333; color:#eee; border-radius:3px; }}
#nav button:hover {{ background:#555; }}
#nav button.active {{ background:#4477AA; color:white; border-color:#4477AA; }}
#counter {{ position:fixed; top:52px; left:10px; color:#888; font-size:12px; z-index:100; }}
.viewer-div {{ position:absolute; top:50px; left:0; }}
</style>
</head>
<body>
<div id="nav">{nav_items}</div>
<div id="counter"></div>
{viewer_divs}
<script>
{all_scripts}

function show(idx) {{
    var n = {n};
    for (var i = 0; i < n; i++) {{
        var el = document.getElementById("viewer_" + i);
        var btn = document.getElementById("btn_" + i);
        if (el) el.style.display = (i === idx) ? "block" : "none";
        if (btn) btn.className = (i === idx) ? "active" : "";
    }}
    document.getElementById("counter").innerHTML =
        (idx + 1) + " / {n}  —  " + document.getElementById("btn_" + idx).textContent;
}}

// Show first by default
show(0);

// Keyboard navigation
document.addEventListener("keydown", function(e) {{
    var current = 0;
    for (var i = 0; i < {n}; i++) {{
        if (document.getElementById("btn_" + i).className === "active") {{ current = i; break; }}
    }}
    if (e.key === "ArrowRight" || e.key === "ArrowDown") {{
        show(Math.min(current + 1, {n} - 1)); e.preventDefault();
    }} else if (e.key === "ArrowLeft" || e.key === "ArrowUp") {{
        show(Math.max(current - 1, 0)); e.preventDefault();
    }}
}});
</script>
</body>
</html>"""

    html_path = os.path.abspath(output_html)
    with open(html_path, "w") as f:
        f.write(html)

    print(f"  Gallery written: {html_path}")
    print(f"  Navigate with buttons or arrow keys (← →)")
    if open_browser:
        webbrowser.open("file://" + html_path)
    return html_path


# ── CLI ──────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Visualize cube file orbital(s) in a web browser via py3Dmol",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Single orbital
  python view_orbital.py orbital.cube

  # Adjust isovalue (lower = larger lobes)
  python view_orbital.py orbital.cube --isoval 0.03

  # Batch gallery with keyboard navigation
  python view_orbital.py cubes/*.cube --gallery

  # Specify output file
  python view_orbital.py orbital.cube -o my_view.html

  # Black background, ball-and-stick model
  python view_orbital.py orbital.cube --style ball-stick
""",
    )
    parser.add_argument("cubes", nargs="+", help="Path(s) to .cube file(s)")
    parser.add_argument("--isoval", type=float, default=0.04,
                        help="Isosurface value (default: 0.04). "
                             "Lower = larger lobes, higher = more compact.")
    parser.add_argument("--opacity", type=float, default=0.85,
                        help="Isosurface opacity 0.0-1.0 (default: 0.85)")
    parser.add_argument("--pos-color", default="blue",
                        help="Color for positive isosurface (default: blue)")
    parser.add_argument("--neg-color", default="red",
                        help="Color for negative isosurface (default: red)")
    parser.add_argument("--bg", default="black",
                        help="Background color (default: black)")
    parser.add_argument("--style", default="stick",
                        choices=["stick", "ball-stick", "sphere"],
                        help="Molecular structure style (default: stick)")
    parser.add_argument("-o", "--output", default=None,
                        help="Output HTML file path")
    parser.add_argument("--gallery", action="store_true",
                        help="Combine multiple cube files into a single "
                             "gallery page with navigation buttons")
    parser.add_argument("--no-open", action="store_true",
                        help="Don't auto-open in browser")
    parser.add_argument("--width", type=int, default=900, help="Viewer width in px")
    parser.add_argument("--height", type=int, default=700, help="Viewer height in px")
    args = parser.parse_args()

    # Expand glob patterns (for shells that don't expand)
    cube_paths = []
    for pattern in args.cubes:
        expanded = glob.glob(pattern)
        if expanded:
            cube_paths.extend(sorted(expanded))
        elif os.path.isfile(pattern):
            cube_paths.append(pattern)
        else:
            print(f"WARNING: no match for {pattern}")

    if not cube_paths:
        print("ERROR: no cube files found.")
        sys.exit(1)

    open_browser = not args.no_open

    if len(cube_paths) == 1 or not args.gallery:
        # Single mode: one HTML per cube file
        html_paths = []
        for i, cp in enumerate(cube_paths):
            out = args.output
            if out is None and len(cube_paths) > 1:
                stem = os.path.splitext(os.path.basename(cp))[0]
                out = f"{stem}_viewer.html"
            html_paths.append(view_cube(
                cube_path=cp,
                isoval=args.isoval,
                opacity=args.opacity,
                pos_color=args.pos_color,
                neg_color=args.neg_color,
                bg_color=args.bg,
                style=args.style,
                width=args.width,
                height=args.height,
                output_html=out,
                open_browser=(open_browser and i == 0),
            ))
    else:
        # Gallery mode: all cubes in one HTML
        view_multi_cubes(
            cube_paths=cube_paths,
            isoval=args.isoval,
            opacity=args.opacity,
            pos_color=args.pos_color,
            neg_color=args.neg_color,
            bg_color=args.bg,
            style=args.style,
            width=args.width,
            height=args.height,
            output_html=args.output or "orbital_gallery.html",
            open_browser=open_browser,
        )


if __name__ == "__main__":
    main()
