"""Selection file I/O helpers for active-space workflows."""

import logging
import os
import sys

logger = logging.getLogger(__name__)


def generate_selection_file(
    cas,
    output_path: str,
    n_electrons: int | None = None,
) -> str:
    """Generate a selection.txt file from CAS active space."""
    indices = sorted(cas.active_indices) if cas.active_indices else []
    nelec = n_electrons if n_electrons is not None else cas.n_electrons
    norb = len(indices)

    lines = [
        "# Active space selection (auto-generated by apex-cas compute)",
        "# Edit n-electrons and indices, then run: apex-cas fcidump",
        f"n-electrons: {nelec}",
        f"n-orbital: {norb}",
    ]

    for i in range(0, len(indices), 10):
        chunk = indices[i:i + 10]
        lines.append(" ".join(str(idx) for idx in chunk))

    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    with open(output_path, "w") as f:
        f.write("\n".join(lines) + "\n")

    logger.info(
        "Selection file written to %s (%d orbitals, %d electrons)",
        output_path,
        norb,
        nelec,
    )
    return os.path.abspath(output_path)


def load_active_selection(filepath: str) -> tuple[list[int], int]:
    """Parse a selection.txt file and return orbital indices + n-electrons."""
    n_electrons = None
    n_orbital = None
    indices = []

    with open(filepath) as f:
        for line in f:
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            if ":" in stripped and not any(
                c.isalpha() for c in stripped.split(":")[0].replace("-", "")
            ):
                parts = stripped.split(":", 1)
                key = parts[0].strip().lower()
                val = parts[1].strip()
                if key == "n-electrons":
                    n_electrons = int(val)
                elif key == "n-orbital":
                    n_orbital = int(val)
                continue
            tokens = stripped.split()
            try:
                indices.extend(int(t) for t in tokens)
            except ValueError:
                if ":" in stripped:
                    parts = stripped.split(":", 1)
                    key = parts[0].strip().lower()
                    val = parts[1].strip()
                    if key == "n-electrons":
                        n_electrons = int(val)
                    elif key == "n-orbital":
                        n_orbital = int(val)

    if n_electrons is None:
        print(f"ERROR: 'n-electrons' not found in {filepath}")
        sys.exit(1)
    if n_orbital is None:
        print(f"ERROR: 'n-orbital' not found in {filepath}")
        sys.exit(1)

    indices = sorted(set(indices))
    if len(indices) != n_orbital:
        print(
            f"ERROR: n-orbital ({n_orbital}) does not match number of indices ({len(indices)})"
        )
        print(f"  Indices found: {indices}")
        sys.exit(1)

    logger.info(
        "Loaded selection from %s: %d orbitals, %d electrons",
        filepath,
        n_orbital,
        n_electrons,
    )
    return indices, n_electrons
