"""Selection-file generation helpers for active-space workflows.

Parsing authority now lives entirely in ``shared.selection_io``. This module is
kept only for staged-CLI selection-file generation.
"""

import logging
import os

logger = logging.getLogger(__name__)


def _generate_selection_file(
    cas,
    output_path: str,
    n_electrons: int | None = None,
) -> str:
    """Generate a ``selection.txt`` file from CAS active-space metadata."""
    indices = sorted(cas.active_indices) if cas.active_indices else []
    nelec = n_electrons if n_electrons is not None else cas.n_electrons
    norb = len(indices)

    lines = [
        "# Active space selection (auto-generated by apex-cas buildcas/compute)",
        "# Edit n-electrons and indices, then run: apex-cas fcidump",
        f"n-electrons: {nelec}",
        f"n-orbital: {norb}",
    ]

    for i in range(0, len(indices), 10):
        chunk = indices[i:i + 10]
        lines.append(" ".join(str(idx) for idx in chunk))

    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    with open(output_path, "w") as f:
        f.write("\n".join(lines) + "\n")

    logger.info(
        "Selection file written to %s (%d orbitals, %d electrons)",
        output_path,
        norb,
        nelec,
    )
    return os.path.abspath(output_path)
